package br.andrew.sap.rovema.model

import br.andrew.sap.rovema.model.romaneio.RomaneioEntradaInsumo
import br.andrew.sap.rovema.model.romaneio.TipoAnalise
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.PropertyNamingStrategy
import com.fasterxml.jackson.databind.annotation.JsonNaming
import java.util.*

@JsonNaming(PropertyNamingStrategy.UpperCamelCaseStrategy::class)
@JsonIgnoreProperties(ignoreUnknown = true)
class RomaneioPesagem(
        val docNum: Int,
        val period: Int,
        val instance: Int,
        val series: Int,
        val handwrtten: String,
        val status: String,
        val requestStatus: String,
        val creator: String,
        val remark: String?,
        val docEntry: Int,
        val canceled: String,
        val logInst: String?,
        val userSign: Int,
        val transfered: String,
        val createDate: String,
        val createTime: String,
        val updateDate: String,
        val updateTime: String,
        val dataSource: String,
        val uDtDescarga: String?,
        val uCodEndereco: String?,
        val uQtdRetida: Int,
        val u_PesagemManual: String,
        val u_PesagemAvulsa: String,
        val u_DataPesagem: String?,
        val u_Moeda: String?,
        val u_TaxaMoeda: Int,
        val u_CodRomaneioOrigem: String?,
        val u_CodParceiro: String?,
        val u_CodItem: String?,
        val u_EnderecoParceiro: String?,
        val u_DtEmissaoNota: String?,
        val u_DtEmissaoNotaCA: String?,
        val u_ReferenciaExterna: String?,
        val u_CodProgramacaoCarga: String?,
        val u_CodDocumento: String?,
        val u_CodDocumentoComp: String?,
        val u_CodDocumentoCA: String?,
        val u_CodContrato: String?,
        val u_CodContratoComplementar: String?,
        val u_CodViagem: String?,
        val u_NumeroTicket: Int?,
        val u_Motorista: String?,
        val u_PlacaCaminhao: String?,
        val u_UFPlaca: String?,
        val u_PlacaCarreta: String?,
        val u_UFPlacaCarreta: String?,
        val u_PlacaCaminhao3: String?,
        val u_UFPlaca3: String?,
        val u_NumeroNota: Int?,
        val u_NumeroNotaCA: String?,
        val u_PesoNota: Double?,
        val u_PesoNotaCA: Double?,
        val u_ValorNota: Int,
        val u_ValorNotaCA: Int,
        val u_PesoBruto: Double,
        val u_PesoTara: Double,
        val u_PesoLiquido: Double?,
        val u_PesoLiquidoDesc: Double?,
        val u_PesoDestinoDesc: Int,
        val u_PesoLiquidoDest: Int,
        val u_Diferenca: Double?,
        val u_MassaTotal: Int,
        val u_EncerradoPor: String?,
        val u_DtEncerramento: String?,
        val u_HrEncerramento: String?,
        val u_Status: String,
        val u_ChaveNota: String?,
        val u_ChaveNotaCA: String?,
        val u_ModeloNota: String?,
        val u_ModeloNotaCA: String?,
        val u_SerieNota: String?,
        val u_SerieNotaCA: String?,
        val u_CadastradoGuardian: String,
        val u_AnaliseConfirmada: String,
        val u_RomaneioImpresso: String,
        val u_DesbloquearGuardian: String,
        val u_AtualizarPesoLiquido: String,
        val u_Volume: Int,
        val u_QtdContratoComp: Int,
        val u_NrGuiaFlorestal: String?,
        val u_CodTransportadora: String?,
        val u_CodMoega: String?,
        val u_ObservacoesNF: String?,
        val u_ObservacoesNFCA: String?,
        val u_ObsRomaneio: String?,
        val u_RecusaCarga: String?,
        val u_QtdRecusada: Int,
        val u_CodVeiculo: String?,
        val u_CodMotorista: String?,
        val u_TipoGrao: String?,
        val u_SubtipoGrao: String?,
        val u_NFPropria: String?,
        val u_PesoHectoEncontrado: Int,
        val u_PesoHectoMelhorado: Int,
        val u_Massa20Graus: Int,
        val u_GrauINPM: Int,
        val u_VolumeLaboratorio: Int,
        val u_DiferencaLabExpedido: Int,
        val u_DiferencaLabExpedidoPct: Int,
        val u_CodFilial: String,
        val u_HrAnaliseLab: String?,
        val u_HrAnalise: String?,
        val u_HoraPesoBruto: String?,
        val u_HoraPesoTara: String?,
        val u_HoraGeracaoNota: String?,
        val u_HoraEntradaPlanta: String?,
        val u_NrBoletimColheita: String?,
        val u_InscricaoEstadual: String?,
        val u_DesbloqueadoPor: String?,
        val u_DataDesbloqueio: String?,
        val u_HoraDesbloqueio: String?,
        val u_JustificativaDesbloqueio: String?,
        val u_ValorFrete: Int,
        val u_CodRomaneioGerador: String?,
        val u_CodOffline: String?,
        val u_Taxa: Int,
        val u_CodDeposito: String?,
        val u_DataUltimoAcerto: String?,
        val u_TaraEmbalagem: Int,
        val u_Impresso: String,
        val u_DtPesagemInicial: String?,
        val u_DtPesagemFinal: String?,
        val u_HrPesagemInicial: String?,
        val u_HrPesagemFinal: String?,
        val u_Estornou: String,
        val u_CodPNClassificador: String?,
        val u_PNClassContrato: String,
        val u_CodOrdemCarregamento: String?,
        val u_CodTipoVeiculo: String?,
        val u_CodArmazem: String?,
        val u_CodDocumentoCreditoPresumido: String?,
        val u_NomeParceiro: String?,
        val u_DescricaoItem: String?,
        val u_CodDepositoTransferencia: String?,
        val u_CodTransferenciaTerceiros: String?
) {

    @JsonProperty("AMFS_RETACollection")
    val tipoAnalise : List<TipoAnalise>? = null


}