package br.andrew.sap.model.sap.documents

import com.fasterxml.jackson.annotation.JsonFormat

@JsonFormat(shape = JsonFormat.Shape.STRING)
enum class DocumentTypes(val value: Int, val label: String) {
    oChartOfAccounts(1, "Plano de Contas"),
    oBusinessPartners(2, "Parceiros de Negócio"),
    oBanks(3, "Bancos"),
    oItems(4, "Itens"),
    oVatGroups(5, "Grupos de Impostos"),
    oPriceLists(6, "Listas de Preço"),
    oSpecialPrices(7, "Preços Especiais"),
    oItemProperties(8, "Propriedades de Item"),
    oBusinessPartnerGroups(10, "Grupos de Parceiros de Negócio"),
    oUsers(12, "Usuários"),
    oInvoices(13, "Nota Fiscal de Saída"),
    oCreditNotes(14, "Devolução de Nota Fiscal de Saída"),
    oDeliveryNotes(15, "Notas de Entrega"),
    oReturns(16, "Devoluções"),
    oOrders(17, "Pedidos de Venda"),
    oPurchaseInvoices(18, "Nota Fiscal de Entrada"),
    oPurchaseCreditNotes(19, "Devolução de Nota Fiscal de Entrada"),
    oPurchaseDeliveryNotes(20, "Notas de Entrega de Compra"),
    oPurchaseReturns(21, "Devoluções de Compra"),
    oPurchaseOrders(22, "Pedidos de Compra"),
    oQuotations(23, "Cotações"),
    oIncomingPayments(24, "Recebimentos"),
    oJournalVouchers(28, "Lançamentos Temporários"),
    oJournalEntries(30, "Lançamentos Contábeis"),
    oStockTakings(31, "Inventários"),
    oContacts(33, "Contatos"),
    oCreditCards(36, "Cartões de Crédito"),
    oCurrencyCodes(37, "Moedas"),
    oPaymentTermsTypes(40, "Condições de Pagamento"),
    oBankPages(42, "Contas Bancárias"),
    oManufacturers(43, "Fabricantes"),
    oVendorPayments(46, "Pagamentos a Fornecedores"),
    oLandedCostsCodes(48, "Custos de Importação"),
    oShippingTypes(49, "Tipos de Frete"),
    oLengthMeasures(50, "Unidades de Comprimento"),
    oWeightMeasures(51, "Unidades de Peso"),
    oItemGroups(52, "Grupos de Itens"),
    oSalesPersons(53, "Vendedores"),
    oCustomsGroups(56, "Grupos Aduaneiros"),
    oChecksforPayment(57, "Cheques"),
    oInventoryGenEntry(59, "Entrada Manual de Estoque"),
    oInventoryGenExit(60, "Saída Manual de Estoque"),
    oWarehouses(64, "Depósitos"),
    oCommissionGroups(65, "Grupos de Comissão"),
    oProductTrees(66, "Fórmulas de Produto"),
    oStockTransfer(67, "Transferência de Estoque"),
    oWorkOrders(68, "Ordens de Trabalho"),
    oCreditPaymentMethods(70, "Métodos de Pagamento - Crédito"),
    oCreditCardPayments(71, "Pagamentos com Cartão"),
    oAlternateCatNum(73, "Nº Catálogo Alternativo"),
    oBudget(77, "Orçamento"),
    oBudgetDistribution(78, "Distribuição de Orçamento"),
    oMessages(81, "Mensagens"),
    oBudgetScenarios(91, "Cenários de Orçamento"),
    oUserDefaultGroups(93, "Grupos Padrão de Usuário"),
    oSalesOpportunities(97, "Oportunidades de Venda"),
    oSalesStages(101, "Etapas de Venda"),
    oActivityTypes(103, "Tipos de Atividade"),
    oActivityLocations(104, "Locais de Atividade"),
    oDrafts(112, "Rascunhos"),
    oDeductionTaxHierarchies(116, "Hierarquia de Imposto Retido"),
    oDeductionTaxGroups(117, "Grupos de Imposto Retido"),
    oAdditionalExpenses(125, "Despesas Adicionais"),
    oSalesTaxAuthorities(126, "Autoridades Fiscais de Venda"),
    oSalesTaxAuthoritiesTypes(127, "Tipos de Autoridade Fiscal"),
    oSalesTaxCodes(128, "Códigos de Imposto de Venda"),
    oQueryCategories(134, "Categorias de Consulta"),
    oFactoringIndicators(138, "Indicadores de Faturamento"),
    oPaymentsDrafts(140, "Rascunhos de Pagamento"),
    oAccountSegmentations(142, "Segmentações Contábeis"),
    oAccountSegmentationCategories(143, "Categorias de Segmentação"),
    oWarehouseLocations(144, "Localizações de Estoque"),
    oForms1099(145, "Formulários 1099"),
    oInventoryCycles(146, "Ciclos de Inventário"),
    oWizardPaymentMethods(147, "Assistente de Métodos de Pagamento"),
    oBPPriorities(150, "Prioridades de PN"),
    oDunningLetters(151, "Cartas de Cobrança"),
    oUserFields(152, "Campos de Usuário"),
    oUserTables(153, "Tabelas de Usuário"),
    oPickLists(156, "Listas de Separação"),
    oPaymentRunExport(158, "Exportação de Execução de Pagamento"),
    oUserQueries(160, "Consultas de Usuário"),
    oMaterialRevaluation(162, "Reavaliação de Material"),
    oCorrectionPurchaseInvoice(163, "Nota de Correção de Compra"),
    oCorrectionPurchaseInvoiceReversal(164, "Estorno de Correção de Compra"),
    oCorrectionInvoice(165, "Nota de Correção"),
    oCorrectionInvoiceReversal(166, "Estorno de Correção"),
    oContractTemplates(170, "Modelos de Contrato"),
    oEmployeesInfo(171, "Informações de Empregados"),
    oCustomerEquipmentCards(176, "Equipamentos do Cliente"),
    oWithholdingTaxCodes(178, "Códigos de Imposto Retido"),
    oBillOfExchangeTransactions(182, "Transações com Duplicatas"),
    oKnowledgeBaseSolutions(189, "Soluções da Base de Conhecimento"),
    oServiceContracts(190, "Contratos de Serviço"),
    oServiceCalls(191, "Chamados de Serviço"),
    oUserKeys(193, "Chaves de Usuário"),
    oQueue(194, "Fila"),
    oSalesForecast(198, "Previsão de Vendas"),
    oTerritories(200, "Territórios"),
    oIndustries(201, "Indústrias"),
    oProductionOrders(202, "Ordens de Produção"),
    oDownPayments(203, "Adiantamentos de Clientes"),
    oPurchaseDownPayments(204, "Adiantamentos de Fornecedores"),
    oPackagesTypes(205, "Tipos de Embalagem"),
    oUserObjectsMD(206, "Objetos de Usuário"),
    oTeams(211, "Equipes"),
    oRelationships(212, "Relacionamentos"),
    oUserPermissionTree(214, "Árvore de Permissões"),
    oActivityStatus(217, "Status da Atividade"),
    oChooseFromList(218, "Lista de Seleção"),
    oFormattedSearches(219, "Pesquisas Formatadas"),
    oAttachments2(221, "Anexos"),
    oUserLanguages(223, "Idiomas de Usuário"),
    oMultiLanguageTranslations(224, "Traduções Multilíngues"),
    oDynamicSystemStrings(229, "Textos do Sistema"),
    oHouseBankAccounts(231, "Contas Bancárias da Empresa"),
    oBusinessPlaces(247, "Filiais"),
    oLocalEra(250, "Era Local"),
    oNotaFiscalCFOP(258, "CFOP"),
    oNotaFiscalCST(259, "CST"),
    oNotaFiscalUsage(260, "Uso da Nota Fiscal"),
    oClosingDateProcedure(261, "Fechamento Contábil"),
    oBPFiscalRegistryID(278, "Registro Fiscal do PN"),
    oSalesTaxInvoice(280, "Nota Fiscal de Imposto de Venda"),
    oPurchaseTaxInvoice(281, "Nota Fiscal de Imposto de Compra"),
    BoRecordset(300, "Conjunto de Registros"),
    BoBridge(305, "Ponte"),
    oStockTransferDraft(1179, "Rascunho de Transferência"),
    oPurchaseQuotations(540000006, "Cotações de Compra"),
    oInventoryTransferRequest(1250000001, "Solicitação de Transferência de Estoque"),
    oPurchaseRequest(1470000113, "Solicitação de Compra")
}
