package br.andrew.sap.json

import br.andrew.sap.infrastructure.odata.OData
import br.andrew.sap.model.entity.UserDefinedObject
import br.andrew.sap.model.sap.partner.BPBranchAssignment
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.KotlinModule
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

class UserDefinedJsonTests  {

    @Test
    fun test(){
        val mapper = ObjectMapper().registerModule(KotlinModule())
        val obj = mapper.readValue(json, jacksonTypeRef<OData>()).tryGetValues<UserDefinedObject>()
    }
    val json = "{\n" +
            "   \"odata.count\" : 1,\n" +
            "   \"odata.metadata\" : \"https://localhost:50000/b1s/v1/\$metadata#UserObjectsMD\",\n" +
            "   \"value\" : [\n" +
            "      {\n" +
            "         \"TableName\" : \"COMISSAO\",\n" +
            "         \"Code\" : \"comissao\",\n" +
            "         \"LogTableName\" : \"ACOMISSAO\",\n" +
            "         \"CanCreateDefaultForm\" : \"tYES\",\n" +
            "         \"ObjectType\" : \"boud_MasterData\",\n" +
            "         \"ExtensionName\" : null,\n" +
            "         \"CanCancel\" : \"tNO\",\n" +
            "         \"CanDelete\" : \"tYES\",\n" +
            "         \"CanLog\" : \"tYES\",\n" +
            "         \"ManageSeries\" : \"tNO\",\n" +
            "         \"CanFind\" : \"tYES\",\n" +
            "         \"CanYearTransfer\" : \"tNO\",\n" +
            "         \"Name\" : \"Comissões\",\n" +
            "         \"CanClose\" : \"tNO\",\n" +
            "         \"OverwriteDllfile\" : \"tYES\",\n" +
            "         \"UseUniqueFormType\" : \"tYES\",\n" +
            "         \"CanArchive\" : \"tNO\",\n" +
            "         \"MenuItem\" : \"tYES\",\n" +
            "         \"MenuCaption\" : \"Comissões\",\n" +
            "         \"FatherMenuID\" : 43541,\n" +
            "         \"Position\" : 1,\n" +
            "         \"MenuUID\" : \"Comissões\",\n" +
            "         \"EnableEnhancedForm\" : \"tYES\",\n" +
            "         \"RebuildEnhancedForm\" : \"tNO\",\n" +
            "         \"FormSRF\" : \"<?xml version=\\\"1.0\\\" encoding=\\\"utf-16\\\"?><Application><forms><action type=\\\"add\\\"><form appformnumber=\\\"-1\\\" FormType=\\\"UDO_FT_comissao\\\" type=\\\"0\\\" BorderStyle=\\\"0\\\" uid=\\\"UDO_F_comissao\\\" title=\\\"Comissões\\\" visible=\\\"1\\\" default_button=\\\"\\\" mode=\\\"3\\\" pane=\\\"1\\\" color=\\\"0\\\" left=\\\"370\\\" top=\\\"127\\\" width=\\\"600\\\" height=\\\"392\\\" AutoManaged=\\\"1\\\" SupportedModes=\\\"15\\\" ObjectType=\\\"comissao\\\"><datasources><dbdatasources><action type=\\\"add\\\"><datasource tablename=\\\"@COMISSAO\\\" /><datasource tablename=\\\"@CONDICOESFV\\\" /><datasource tablename=\\\"@LIBERAPARA\\\" /></action></dbdatasources><userdatasources><action type=\\\"add\\\"><datasource uid=\\\"FolderDS\\\" type=\\\"9\\\" size=\\\"10\\\" /></action></userdatasources></datasources><Menus /><items><action type=\\\"add\\\"><item uid=\\\"0_U_S\\\" type=\\\"8\\\" left=\\\"6\\\" tab_order=\\\"0\\\" width=\\\"121\\\" top=\\\"6\\\" height=\\\"14\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"Código\\\" linkto=\\\"0_U_E\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific caption=\\\"Código\\\" /></item><item uid=\\\"0_U_E\\\" type=\\\"16\\\" left=\\\"127\\\" tab_order=\\\"0\\\" width=\\\"148\\\" top=\\\"6\\\" height=\\\"14\\\" visible=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"Código\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific TabOrder=\\\"5\\\"><databind databound=\\\"1\\\" table=\\\"@COMISSAO\\\" alias=\\\"Code\\\" /></specific></item><item uid=\\\"1_U_S\\\" type=\\\"8\\\" left=\\\"306\\\" tab_order=\\\"0\\\" width=\\\"121\\\" top=\\\"6\\\" height=\\\"14\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"Descrição\\\" linkto=\\\"1_U_E\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific caption=\\\"Descrição\\\" /></item><item uid=\\\"1_U_E\\\" type=\\\"16\\\" left=\\\"427\\\" tab_order=\\\"0\\\" width=\\\"148\\\" top=\\\"6\\\" height=\\\"14\\\" visible=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"Descrição\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific TabOrder=\\\"6\\\"><databind databound=\\\"1\\\" table=\\\"@COMISSAO\\\" alias=\\\"Name\\\" /></specific></item><item uid=\\\"13_U_S\\\" type=\\\"8\\\" left=\\\"6\\\" tab_order=\\\"0\\\" width=\\\"121\\\" top=\\\"21\\\" height=\\\"14\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"comissão em porcentagem\\\" linkto=\\\"13_U_E\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific caption=\\\"comissão em porcentagem\\\" /></item><item uid=\\\"13_U_E\\\" type=\\\"16\\\" left=\\\"127\\\" tab_order=\\\"0\\\" width=\\\"148\\\" top=\\\"21\\\" height=\\\"14\\\" visible=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"comissão em porcentagem\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific TabOrder=\\\"7\\\"><databind databound=\\\"1\\\" table=\\\"@COMISSAO\\\" alias=\\\"U_porcentagem\\\" /></specific></item><item uid=\\\"14_U_S\\\" type=\\\"8\\\" left=\\\"306\\\" tab_order=\\\"0\\\" width=\\\"121\\\" top=\\\"21\\\" height=\\\"14\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"Desconto (%) do vendedor\\\" linkto=\\\"14_U_E\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific caption=\\\"Desconto (%) do vendedor\\\" /></item><item uid=\\\"14_U_E\\\" type=\\\"16\\\" left=\\\"427\\\" tab_order=\\\"0\\\" width=\\\"148\\\" top=\\\"21\\\" height=\\\"14\\\" visible=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"Desconto (%) do vendedor\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific TabOrder=\\\"8\\\"><databind databound=\\\"1\\\" table=\\\"@COMISSAO\\\" alias=\\\"U_desconto\\\" /></specific></item><item uid=\\\"15_U_S\\\" type=\\\"8\\\" left=\\\"6\\\" tab_order=\\\"0\\\" width=\\\"121\\\" top=\\\"36\\\" height=\\\"14\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"Comissão regressiva?\\\" linkto=\\\"15_U_Cb\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific caption=\\\"Comissão regressiva?\\\" /></item><item uid=\\\"15_U_Cb\\\" type=\\\"113\\\" left=\\\"127\\\" tab_order=\\\"0\\\" width=\\\"148\\\" top=\\\"36\\\" height=\\\"14\\\" visible=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" description=\\\"Comissão regressiva?\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific TabOrder=\\\"9\\\"><databind databound=\\\"1\\\" table=\\\"@COMISSAO\\\" alias=\\\"U_regressiva\\\" /></specific></item><item uid=\\\"1\\\" type=\\\"4\\\" left=\\\"6\\\" tab_order=\\\"\\\" width=\\\"65\\\" top=\\\"332\\\" height=\\\"19\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific caption=\\\"OK\\\" /></item><item uid=\\\"2\\\" type=\\\"4\\\" left=\\\"76\\\" tab_order=\\\"\\\" width=\\\"65\\\" top=\\\"332\\\" height=\\\"19\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific caption=\\\"Cancelar\\\" /></item><item uid=\\\"0_U_FD\\\" type=\\\"99\\\" left=\\\"6\\\" tab_order=\\\"\\\" width=\\\"116\\\" top=\\\"88\\\" height=\\\"19\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific caption=\\\"Linha condiçoes\\\" AffectsFormMode=\\\"1\\\" val_on=\\\"Y\\\" val_off=\\\"N\\\" pane=\\\"1\\\" AutoPaneSelection=\\\"1\\\"><databind databound=\\\"1\\\" table=\\\"\\\" alias=\\\"FolderDS\\\" /></specific></item><item uid=\\\"1_U_FD\\\" type=\\\"99\\\" left=\\\"122\\\" tab_order=\\\"\\\" width=\\\"116\\\" top=\\\"88\\\" height=\\\"19\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific caption=\\\"Libera para\\\" AffectsFormMode=\\\"1\\\" val_on=\\\"Y\\\" val_off=\\\"N\\\" pane=\\\"2\\\" AutoPaneSelection=\\\"1\\\"><databind databound=\\\"1\\\" table=\\\"\\\" alias=\\\"FolderDS\\\" /></specific></item><item uid=\\\"U_RC\\\" type=\\\"100\\\" left=\\\"5\\\" tab_order=\\\"\\\" width=\\\"570\\\" top=\\\"106\\\" height=\\\"207\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"0\\\" to_pane=\\\"0\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /></item><item uid=\\\"0_U_G\\\" type=\\\"127\\\" left=\\\"15\\\" tab_order=\\\"\\\" width=\\\"555\\\" top=\\\"133\\\" height=\\\"163\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"1\\\" to_pane=\\\"1\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific SelectionMode=\\\"2\\\"><columns><action type=\\\"add\\\"><column uid=\\\"#\\\" type=\\\"16\\\" title=\\\"#\\\" description=\\\"#\\\" visible=\\\"1\\\" AffectsFormMode=\\\"1\\\" width=\\\"20\\\" disp_desc=\\\"0\\\" editable=\\\"0\\\" right_just=\\\"0\\\" val_on=\\\"Y\\\" val_off=\\\"N\\\" backcolor=\\\"-1\\\" forecolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" IsAutoGenerated=\\\"1\\\" /><column uid=\\\"C_0_1\\\" type=\\\"16\\\" title=\\\"Juros (%)\\\" description=\\\"Juros (%)\\\" visible=\\\"1\\\" AffectsFormMode=\\\"1\\\" width=\\\"100\\\" disp_desc=\\\"0\\\" right_just=\\\"0\\\" val_on=\\\"Y\\\" val_off=\\\"N\\\" backcolor=\\\"-1\\\" forecolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" IsAutoGenerated=\\\"1\\\"><databind databound=\\\"1\\\" table=\\\"@CONDICOESFV\\\" alias=\\\"U_juros\\\" /></column><column uid=\\\"C_0_2\\\" type=\\\"16\\\" title=\\\"Prazo\\\" description=\\\"Prazo\\\" visible=\\\"1\\\" AffectsFormMode=\\\"1\\\" width=\\\"456\\\" disp_desc=\\\"0\\\" right_just=\\\"0\\\" val_on=\\\"Y\\\" val_off=\\\"N\\\" backcolor=\\\"-1\\\" forecolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" IsAutoGenerated=\\\"1\\\"><databind databound=\\\"1\\\" table=\\\"@CONDICOESFV\\\" alias=\\\"U_prazo\\\" /></column></action></columns></specific></item><item uid=\\\"1_U_G\\\" type=\\\"127\\\" left=\\\"15\\\" tab_order=\\\"\\\" width=\\\"555\\\" top=\\\"133\\\" height=\\\"163\\\" visible=\\\"1\\\" enabled=\\\"1\\\" from_pane=\\\"2\\\" to_pane=\\\"2\\\" disp_desc=\\\"\\\" right_just=\\\"0\\\" linkto=\\\"\\\" forecolor=\\\"-1\\\" backcolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" supp_zeros=\\\"0\\\" AffectsFormMode=\\\"1\\\" IsAutoGenerated=\\\"1\\\"><AutoManagedAttribute /><specific SelectionMode=\\\"2\\\"><columns><action type=\\\"add\\\"><column uid=\\\"#\\\" type=\\\"16\\\" title=\\\"#\\\" description=\\\"#\\\" visible=\\\"1\\\" AffectsFormMode=\\\"1\\\" width=\\\"20\\\" disp_desc=\\\"0\\\" editable=\\\"0\\\" right_just=\\\"0\\\" val_on=\\\"Y\\\" val_off=\\\"N\\\" backcolor=\\\"-1\\\" forecolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" IsAutoGenerated=\\\"1\\\" /><column uid=\\\"C_1_1\\\" type=\\\"113\\\" title=\\\"Filial\\\" description=\\\"Filial\\\" visible=\\\"1\\\" AffectsFormMode=\\\"1\\\" width=\\\"100\\\" disp_desc=\\\"0\\\" right_just=\\\"0\\\" val_on=\\\"Y\\\" val_off=\\\"N\\\" backcolor=\\\"-1\\\" forecolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" IsAutoGenerated=\\\"1\\\"><databind databound=\\\"1\\\" table=\\\"@LIBERAPARA\\\" alias=\\\"U_Filial\\\" /></column><column uid=\\\"C_1_2\\\" type=\\\"16\\\" title=\\\"Vendedor\\\" description=\\\"Vendedor\\\" visible=\\\"1\\\" AffectsFormMode=\\\"1\\\" width=\\\"100\\\" disp_desc=\\\"0\\\" right_just=\\\"0\\\" val_on=\\\"Y\\\" val_off=\\\"N\\\" backcolor=\\\"-1\\\" forecolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" IsAutoGenerated=\\\"1\\\"><databind databound=\\\"1\\\" table=\\\"@LIBERAPARA\\\" alias=\\\"U_vendedor\\\" /></column><column uid=\\\"C_1_3\\\" type=\\\"16\\\" title=\\\"Filial\\\" description=\\\"Filial\\\" visible=\\\"1\\\" AffectsFormMode=\\\"1\\\" width=\\\"356\\\" disp_desc=\\\"0\\\" right_just=\\\"0\\\" val_on=\\\"Y\\\" val_off=\\\"N\\\" backcolor=\\\"-1\\\" forecolor=\\\"-1\\\" text_style=\\\"0\\\" font_size=\\\"-1\\\" IsAutoGenerated=\\\"1\\\"><databind databound=\\\"1\\\" table=\\\"@LIBERAPARA\\\" alias=\\\"U_filialteste\\\" /></column></action></columns></specific></item></action></items><ChooseFromListCollection /><DataBrowser BrowseBy=\\\"0_U_E\\\" /><Settings Enabled=\\\"1\\\" EnableRowFormat=\\\"1\\\" /><items><action type=\\\"group\\\"><item uid=\\\"0_U_FD\\\" IsAutoGenerated=\\\"0\\\" /><item uid=\\\"1_U_FD\\\" IsAutoGenerated=\\\"0\\\" /></action></items></form></action></forms></Application>\",\n" +
            "         \"UserObjectMD_ChildTables\" : [\n" +
            "            {\n" +
            "               \"SonNumber\" : 1,\n" +
            "               \"TableName\" : \"CONDICOESFV\",\n" +
            "               \"LogTableName\" : \"ACONDICOESFV\",\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ObjectName\" : \"CONDICOESFV\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"SonNumber\" : 2,\n" +
            "               \"TableName\" : \"LIBERAPARA\",\n" +
            "               \"LogTableName\" : \"ALIBERAPARA\",\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ObjectName\" : \"LIBERAPARA\"\n" +
            "            }\n" +
            "         ],\n" +
            "         \"UserObjectMD_FindColumns\" : [\n" +
            "            {\n" +
            "               \"ColumnNumber\" : 1,\n" +
            "               \"ColumnAlias\" : \"Code\",\n" +
            "               \"ColumnDescription\" : \"código\",\n" +
            "               \"Code\" : \"comissao\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"ColumnNumber\" : 2,\n" +
            "               \"ColumnAlias\" : \"Name\",\n" +
            "               \"ColumnDescription\" : \"Name\",\n" +
            "               \"Code\" : \"comissao\"\n" +
            "            }\n" +
            "         ],\n" +
            "         \"UserObjectMD_FormColumns\" : [\n" +
            "            {\n" +
            "               \"FormColumnAlias\" : \"U_Filial\",\n" +
            "               \"FormColumnDescription\" : \"Filial\",\n" +
            "               \"FormColumnNumber\" : 1,\n" +
            "               \"SonNumber\" : 2,\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"FormColumnAlias\" : \"U_vendedor\",\n" +
            "               \"FormColumnDescription\" : \"Vendedor\",\n" +
            "               \"FormColumnNumber\" : 2,\n" +
            "               \"SonNumber\" : 2,\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"FormColumnAlias\" : \"U_filialteste\",\n" +
            "               \"FormColumnDescription\" : \"Filial\",\n" +
            "               \"FormColumnNumber\" : 3,\n" +
            "               \"SonNumber\" : 2,\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"FormColumnAlias\" : \"Code\",\n" +
            "               \"FormColumnDescription\" : \"Código\",\n" +
            "               \"FormColumnNumber\" : 4,\n" +
            "               \"SonNumber\" : 0,\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"FormColumnAlias\" : \"Name\",\n" +
            "               \"FormColumnDescription\" : \"Descrição\",\n" +
            "               \"FormColumnNumber\" : 5,\n" +
            "               \"SonNumber\" : 0,\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"FormColumnAlias\" : \"U_porcentagem\",\n" +
            "               \"FormColumnDescription\" : \"comissão em porcentagem\",\n" +
            "               \"FormColumnNumber\" : 6,\n" +
            "               \"SonNumber\" : 0,\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"FormColumnAlias\" : \"U_desconto\",\n" +
            "               \"FormColumnDescription\" : \"Desconto (%) do vendedor\",\n" +
            "               \"FormColumnNumber\" : 7,\n" +
            "               \"SonNumber\" : 0,\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"FormColumnAlias\" : \"U_regressiva\",\n" +
            "               \"FormColumnDescription\" : \"Comissão regressiva?\",\n" +
            "               \"FormColumnNumber\" : 8,\n" +
            "               \"SonNumber\" : 0,\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            }\n" +
            "         ],\n" +
            "         \"UserObjectMD_EnhancedFormColumns\" : [\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 1,\n" +
            "               \"ChildNumber\" : 1,\n" +
            "               \"ColumnAlias\" : \"Code\",\n" +
            "               \"ColumnDescription\" : \"Codigo\",\n" +
            "               \"ColumnIsUsed\" : \"tNO\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 2,\n" +
            "               \"ChildNumber\" : 1,\n" +
            "               \"ColumnAlias\" : \"LineId\",\n" +
            "               \"ColumnDescription\" : \"LineId\",\n" +
            "               \"ColumnIsUsed\" : \"tNO\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 3,\n" +
            "               \"ChildNumber\" : 1,\n" +
            "               \"ColumnAlias\" : \"Object\",\n" +
            "               \"ColumnDescription\" : \"Object\",\n" +
            "               \"ColumnIsUsed\" : \"tNO\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 4,\n" +
            "               \"ChildNumber\" : 1,\n" +
            "               \"ColumnAlias\" : \"LogInst\",\n" +
            "               \"ColumnDescription\" : \"LogInst\",\n" +
            "               \"ColumnIsUsed\" : \"tNO\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 5,\n" +
            "               \"ChildNumber\" : 1,\n" +
            "               \"ColumnAlias\" : \"U_desconto\",\n" +
            "               \"ColumnDescription\" : \"Desconto (%)\",\n" +
            "               \"ColumnIsUsed\" : \"tNO\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 6,\n" +
            "               \"ChildNumber\" : 1,\n" +
            "               \"ColumnAlias\" : \"U_juros\",\n" +
            "               \"ColumnDescription\" : \"Juros (%)\",\n" +
            "               \"ColumnIsUsed\" : \"tYES\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 7,\n" +
            "               \"ChildNumber\" : 1,\n" +
            "               \"ColumnAlias\" : \"U_prazo\",\n" +
            "               \"ColumnDescription\" : \"Prazo\",\n" +
            "               \"ColumnIsUsed\" : \"tYES\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 1,\n" +
            "               \"ChildNumber\" : 2,\n" +
            "               \"ColumnAlias\" : \"Code\",\n" +
            "               \"ColumnDescription\" : \"Code\",\n" +
            "               \"ColumnIsUsed\" : \"tNO\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 2,\n" +
            "               \"ChildNumber\" : 2,\n" +
            "               \"ColumnAlias\" : \"LineId\",\n" +
            "               \"ColumnDescription\" : \"LineId\",\n" +
            "               \"ColumnIsUsed\" : \"tNO\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 3,\n" +
            "               \"ChildNumber\" : 2,\n" +
            "               \"ColumnAlias\" : \"Object\",\n" +
            "               \"ColumnDescription\" : \"Object\",\n" +
            "               \"ColumnIsUsed\" : \"tNO\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 4,\n" +
            "               \"ChildNumber\" : 2,\n" +
            "               \"ColumnAlias\" : \"LogInst\",\n" +
            "               \"ColumnDescription\" : \"LogInst\",\n" +
            "               \"ColumnIsUsed\" : \"tNO\",\n" +
            "               \"Editable\" : \"tNO\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 5,\n" +
            "               \"ChildNumber\" : 2,\n" +
            "               \"ColumnAlias\" : \"U_Filial\",\n" +
            "               \"ColumnDescription\" : \"Filial\",\n" +
            "               \"ColumnIsUsed\" : \"tYES\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 6,\n" +
            "               \"ChildNumber\" : 2,\n" +
            "               \"ColumnAlias\" : \"U_vendedor\",\n" +
            "               \"ColumnDescription\" : \"Vendedor\",\n" +
            "               \"ColumnIsUsed\" : \"tYES\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            },\n" +
            "            {\n" +
            "               \"Code\" : \"comissao\",\n" +
            "               \"ColumnNumber\" : 7,\n" +
            "               \"ChildNumber\" : 2,\n" +
            "               \"ColumnAlias\" : \"U_filialteste\",\n" +
            "               \"ColumnDescription\" : \"Filial\",\n" +
            "               \"ColumnIsUsed\" : \"tYES\",\n" +
            "               \"Editable\" : \"tYES\"\n" +
            "            }\n" +
            "         ]\n" +
            "      }\n" +
            "   ]\n" +
            "}\n"
}
