	SELECT
    "U_ORD_CARREGAMENTO" as DocEntry,
	count(DISTINCT "DocEntry") as docEntryQuantity,
	sum("Weight1") as Weight1
FROM
	RDR1
WHERE
    "U_ORD_CARREGAMENTO" = :p1
    OR "U_ORD_CARREGAMENTO" = :p2
    OR "U_ORD_CARREGAMENTO" = :p3
    OR "U_ORD_CARREGAMENTO" = :p3
    OR "U_ORD_CARREGAMENTO" = :p4
    OR "U_ORD_CARREGAMENTO" = :p5
    OR "U_ORD_CARREGAMENTO" = :p6
    OR "U_ORD_CARREGAMENTO" = :p7
    OR "U_ORD_CARREGAMENTO" = :p8
    OR "U_ORD_CARREGAMENTO" = :p9
    OR "U_ORD_CARREGAMENTO" = :p10
    OR "U_ORD_CARREGAMENTO" = :p11
    OR "U_ORD_CARREGAMENTO" = :p12
    OR "U_ORD_CARREGAMENTO" = :p13
    OR "U_ORD_CARREGAMENTO" = :p14
    OR "U_ORD_CARREGAMENTO" = :p15
    OR "U_ORD_CARREGAMENTO" = :p16
    OR "U_ORD_CARREGAMENTO" = :p17
    OR "U_ORD_CARREGAMENTO" = :p18
    OR "U_ORD_CARREGAMENTO" = :p19
    OR "U_ORD_CARREGAMENTO" = :p20
GROUP BY "U_ORD_CARREGAMENTO"