package br.andrew.sap.model.estoque

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.databind.PropertyNamingStrategies
import com.fasterxml.jackson.databind.annotation.JsonNaming

@JsonNaming(PropertyNamingStrategies.UpperCamelCaseStrategy::class)
@JsonIgnoreProperties(ignoreUnknown = true)
class ItemWarehouseInfo (
    //val ItemCode: String,
    val WarehouseCode: String,
//    val MinimalStock: Double,
//    val MaximalStock: Double,
//    val MinimalOrder: Double,
//    val StandardAveragePrice: Double,
//    val Locked: YesNo,
//    val InventoryAccount: String?,
//    val CostAccount: String?,
//    val TransferAccount: String?,
//    val RevenuesAccount: String?,
//    val VarienceAccount: String?,
//    val DecreasingAccount: String?,
//    val IncreasingAccount: String?,
//    val ReturningAccount: String?,
//    val ExpensesAccount: String?,
//    val EURevenuesAccount: String?,
//    val ForeignRevenueAcc: String?,
//    val ForeignExpensAcc: String?,
//    val ExemptIncomeAcc: String?,
//    val PriceDifferenceAcc: String?,
//    val InStock: Double,
//    val Committed: Double,
//    val Ordered: Double,
//    val CountedQuantity: Double,
//    val WasCounted: String,
//    val UserSignature: Int,
//    val Counted: Double,
//    val ExpenseClearingAct: String?,
//    val PurchaseCreditAcc: String?,
//    val ForeignPurchaseCreditAcc: String?,
//    val SalesCreditAcc: String?,
//    val SalesCreditEUAcc: String?,
//    val ExemptedCredits: String?,
//    val SalesCreditForeignAcc: String?,
//    val ExpenseOffsettingAccount: String?,
//    val WipAccount: String?,
//    val ExchangeRateDifferencesAcct: String?,
//    val GoodsClearingAcct: String?,
//    val NegativeInventoryAdjustmentAccount: String?,
//    val CostInflationOffsetAccount: String?,
//    val GLDecreaseAcct: String?,
//    val GLIncreaseAcct: String?,
//    val PAReturnAcct: String?,
//    val PurchaseAcct: String?,
//    val PurchaseOffsetAcct: String?,
//    val ShippedGoodsAccount: String?,
//    val StockInflationOffsetAccount: String?,
//    val StockInflationAdjustAccount: String?,
//    val VATInRevenueAccount: String?,
//    val WipVarianceAccount: String?,
//    val CostInflationAccount: String?,
//    val WHIncomingCenvatAccount: String?,
//    val WHOutgoingCenvatAccount: String?,
//    val StockInTransitAccount: String?,
//    val WipOffsetProfitAndLossAccount: String?,
//    val InventoryOffsetProfitAndLossAccount: String?,
//    val DefaultBin: String?,
//    val DefaultBinEnforced: String,
//    val PurchaseBalanceAccount: String?,
//    val IndEscala: String,
//    val U_TX_TipoMaterial: String?,
//    val U_TX_FonteProduto: String?,
//    val U_TX_AliqIcmsWH: String?,
//    val ItemCycleCounts: List<Any>
)
