package br.andrew.sap.model.entity

enum class LinkedSystemObject {
    ulChartOfAccounts,
    ulBusinessPartners,
    ulBanks,
    ulItems,
    ulUsers,
    ulInvoices,
    ulCreditNotes,
    ulDeliveryNotes,
    ulReturns,
    ulOrders,
    ulPurchaseInvoices,
    ulPurchaseCreditNotes,
    ulPurchaseDeliveryNotes,
    ulPurchaseReturns,
    ulPurchaseOrders,
    ulQuotations,
    ulIncomingPayments,
    ulDepositsService,
    ulJournalEntries,
    ulContacts,
    ulVendorPayments,
    ulChecksforPayment,
    ulInventoryGenEntry,
    ulInventoryGenExit,
    ulWarehouses,
    ulProductTrees,
    ulStockTransfer,
    ulSalesOpportunities,
    ulDrafts,
    ulMaterialRevaluation,
    ulEmployeesInfo,
    ulCustomerEquipmentCards,
    ulServiceContracts,
    ulServiceCalls,
    ulProductionOrders,
    ulInventoryTransferRequest,
    ulBlanketAgreementsService,
    ulProjectManagementService,
    ulReturnRequest,
    ulGoodsReturnRequest,
    ulSalesEmployee,
    //faltava no enum - o campo "prazo" de @CONDICOESFV ja existe no SAP com esse
    //link (criado antes dessa sessao) e o findOrCreate quebrava ao tentar
    //desserializar o campo existente pra checar se precisa criar
    ulPaymentTerms
}