package br.andrew.sap.rovema.json

import br.andrew.sap.rovema.model.RomaneioPesagem
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.KotlinModule
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.junit.jupiter.api.Test

class RomaneioPesagemJsonTest {

    @Test
    fun test(){
        val mapper = ObjectMapper().registerModule(KotlinModule())
        val obj = mapper.readValue(json, jacksonTypeRef<List<RomaneioPesagem>>())
    }

    val json = "[\n" +
            "   {\n" +
            "      \"DocNum\":2105,\n" +
            "      \"Period\":28,\n" +
            "      \"Instance\":0,\n" +
            "      \"Series\":-1,\n" +
            "      \"Handwrtten\":\"N\",\n" +
            "      \"Status\":\"O\",\n" +
            "      \"RequestStatus\":\"W\",\n" +
            "      \"Creator\":\"BALANCA.SN\",\n" +
            "      \"Remark\":null,\n" +
            "      \"DocEntry\":2105,\n" +
            "      \"Canceled\":\"N\",\n" +
            "      \"Object\":\"AMFS_UDO_RETR\",\n" +
            "      \"LogInst\":null,\n" +
            "      \"UserSign\":94,\n" +
            "      \"Transfered\":\"N\",\n" +
            "      \"CreateDate\":\"2023-02-09\",\n" +
            "      \"CreateTime\":\"15:40:00\",\n" +
            "      \"UpdateDate\":\"2023-02-09\",\n" +
            "      \"UpdateTime\":\"15:42:00\",\n" +
            "      \"DataSource\":\"I\",\n" +
            "      \"U_DtDescarga\":null,\n" +
            "      \"U_CodEndereco\":null,\n" +
            "      \"U_QtdRetida\":0.0,\n" +
            "      \"U_PesagemManual\":\"Y\",\n" +
            "      \"U_PesagemAvulsa\":\"N\",\n" +
            "      \"U_DataPesagem\":\"2023-02-09\",\n" +
            "      \"U_Moeda\":null,\n" +
            "      \"U_TaxaMoeda\":0.0,\n" +
            "      \"U_CodRomaneioOrigem\":null,\n" +
            "      \"U_CodParceiro\":\"CLI0000575\",\n" +
            "      \"U_CodItem\":\"GRA0000002\",\n" +
            "      \"U_EnderecoParceiro\":\"ENTREGA\",\n" +
            "      \"U_DtEmissaoNota\":null,\n" +
            "      \"U_DtEmissaoNotaCA\":null,\n" +
            "      \"U_ReferenciaExterna\":null,\n" +
            "      \"U_CodProgramacaoCarga\":null,\n" +
            "      \"U_CodDocumento\":null,\n" +
            "      \"U_CodDocumentoComp\":null,\n" +
            "      \"U_CodDocumentoCA\":null,\n" +
            "      \"U_CodContrato\":null,\n" +
            "      \"U_CodContratoComplementar\":null,\n" +
            "      \"U_CodViagem\":null,\n" +
            "      \"U_NumeroTicket\":null,\n" +
            "      \"U_Motorista\":\"SILVIO CESAR CORTTI\",\n" +
            "      \"U_PlacaCaminhao\":\"LXX-8159\",\n" +
            "      \"U_UFPlaca\":\"SC\",\n" +
            "      \"U_PlacaCarreta\":\"MQN-3H03\",\n" +
            "      \"U_UFPlacaCarreta\":\"RO\",\n" +
            "      \"U_PlacaCaminhao3\":\"\",\n" +
            "      \"U_UFPlaca3\":\"\",\n" +
            "      \"U_NumeroNota\":null,\n" +
            "      \"U_NumeroNotaCA\":null,\n" +
            "      \"U_PesoNota\":0.0,\n" +
            "      \"U_PesoNotaCA\":0.0,\n" +
            "      \"U_ValorNota\":0.0,\n" +
            "      \"U_ValorNotaCA\":0.0,\n" +
            "      \"U_PesoBruto\":0.0,\n" +
            "      \"U_PesoTara\":16350.0,\n" +
            "      \"U_PesoLiquido\":-16350.0,\n" +
            "      \"U_PesoLiquidoDesc\":-16350.0,\n" +
            "      \"U_PesoDestinoDesc\":0.0,\n" +
            "      \"U_PesoLiquidoDest\":0.0,\n" +
            "      \"U_Diferenca\":-16350.0,\n" +
            "      \"U_MassaTotal\":0.0,\n" +
            "      \"U_EncerradoPor\":null,\n" +
            "      \"U_DtEncerramento\":null,\n" +
            "      \"U_HrEncerramento\":null,\n" +
            "      \"U_Status\":\"A\",\n" +
            "      \"U_ChaveNota\":null,\n" +
            "      \"U_ChaveNotaCA\":null,\n" +
            "      \"U_ModeloNota\":null,\n" +
            "      \"U_ModeloNotaCA\":null,\n" +
            "      \"U_SerieNota\":null,\n" +
            "      \"U_SerieNotaCA\":null,\n" +
            "      \"U_CadastradoGuardian\":\"N\",\n" +
            "      \"U_AnaliseConfirmada\":\"N\",\n" +
            "      \"U_RomaneioImpresso\":\"N\",\n" +
            "      \"U_DesbloquearGuardian\":\"N\",\n" +
            "      \"U_AtualizarPesoLiquido\":\"N\",\n" +
            "      \"U_Volume\":0.0,\n" +
            "      \"U_QtdContratoComp\":0.0,\n" +
            "      \"U_NrGuiaFlorestal\":null,\n" +
            "      \"U_CodTransportadora\":\"\",\n" +
            "      \"U_CodMoega\":null,\n" +
            "      \"U_ObservacoesNF\":null,\n" +
            "      \"U_ObservacoesNFCA\":null,\n" +
            "      \"U_ObsRomaneio\":\"EXPEDICA DE SOJA EM GRAOS NO SECADOR \\rORDEM DE NUMERO 142\",\n" +
            "      \"U_RecusaCarga\":null,\n" +
            "      \"U_QtdRecusada\":0.0,\n" +
            "      \"U_CodVeiculo\":\"173\",\n" +
            "      \"U_CodMotorista\":\"675\",\n" +
            "      \"U_TipoGrao\":null,\n" +
            "      \"U_SubtipoGrao\":null,\n" +
            "      \"U_NFPropria\":null,\n" +
            "      \"U_PesoHectoEncontrado\":0.0,\n" +
            "      \"U_PesoHectoMelhorado\":0.0,\n" +
            "      \"U_Massa20Graus\":0.0,\n" +
            "      \"U_GrauINPM\":0.0,\n" +
            "      \"U_VolumeLaboratorio\":0.0,\n" +
            "      \"U_DiferencaLabExpedido\":0.0,\n" +
            "      \"U_DiferencaLabExpedidoPct\":0.0,\n" +
            "      \"U_CodFilial\":\"2\",\n" +
            "      \"U_HrAnaliseLab\":null,\n" +
            "      \"U_HrAnalise\":null,\n" +
            "      \"U_HoraPesoBruto\":null,\n" +
            "      \"U_HoraPesoTara\":\"15:40:00\",\n" +
            "      \"U_HoraGeracaoNota\":null,\n" +
            "      \"U_HoraEntradaPlanta\":null,\n" +
            "      \"U_NrBoletimColheita\":null,\n" +
            "      \"U_InscricaoEstadual\":null,\n" +
            "      \"U_DesbloqueadoPor\":null,\n" +
            "      \"U_DataDesbloqueio\":null,\n" +
            "      \"U_HoraDesbloqueio\":null,\n" +
            "      \"U_JustificativaDesbloqueio\":null,\n" +
            "      \"U_ValorFrete\":0.0,\n" +
            "      \"U_CodRomaneioGerador\":null,\n" +
            "      \"U_CodOffline\":null,\n" +
            "      \"U_Taxa\":0.0,\n" +
            "      \"U_CodDeposito\":null,\n" +
            "      \"U_DataUltimoAcerto\":null,\n" +
            "      \"U_TaraEmbalagem\":0.0,\n" +
            "      \"U_Impresso\":\"N\",\n" +
            "      \"U_DtPesagemInicial\":null,\n" +
            "      \"U_DtPesagemFinal\":null,\n" +
            "      \"U_HrPesagemInicial\":null,\n" +
            "      \"U_HrPesagemFinal\":null,\n" +
            "      \"U_Estornou\":\"N\",\n" +
            "      \"U_CodPNClassificador\":null,\n" +
            "      \"U_PNClassContrato\":\"N\",\n" +
            "      \"U_CodOrdemCarregamento\":null,\n" +
            "      \"U_CodTipoVeiculo\":\"1\",\n" +
            "      \"U_CodArmazem\":null,\n" +
            "      \"U_CodDocumentoCreditoPresumido\":null,\n" +
            "      \"U_NomeParceiro\":\"RODRIGO SILVEIRA\",\n" +
            "      \"U_DescricaoItem\":\"SOJA EM GRAOS\",\n" +
            "      \"U_CodDepositoTransferencia\":null,\n" +
            "      \"U_CodTransferenciaTerceiros\":null,\n" +
            "      \"U_CodLactoFinanceiro\":null,\n" +
            "      \"AMFS_RETACollection\":[\n" +
            "         {\n" +
            "            \"DocEntry\":2105,\n" +
            "            \"LineId\":1,\n" +
            "            \"VisOrder\":1,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodTipoAnalise\":\"5\",\n" +
            "            \"U_DscTipoAnalise\":\"UMIDADE SOJA 22/23\",\n" +
            "            \"U_ValorEncontrado\":0.0,\n" +
            "            \"U_ValorDestino\":0.0,\n" +
            "            \"U_DscUnidadeMedida\":null,\n" +
            "            \"U_DescontoPeso\":0.0,\n" +
            "            \"U_CodFaixaDesconto\":null,\n" +
            "            \"U_DescontoDestino\":0.0\n" +
            "         },\n" +
            "         {\n" +
            "            \"DocEntry\":2105,\n" +
            "            \"LineId\":2,\n" +
            "            \"VisOrder\":1,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodTipoAnalise\":\"7\",\n" +
            "            \"U_DscTipoAnalise\":\"IMPUREZA SOJA 22/23\",\n" +
            "            \"U_ValorEncontrado\":0.0,\n" +
            "            \"U_ValorDestino\":0.0,\n" +
            "            \"U_DscUnidadeMedida\":null,\n" +
            "            \"U_DescontoPeso\":0.0,\n" +
            "            \"U_CodFaixaDesconto\":null,\n" +
            "            \"U_DescontoDestino\":0.0\n" +
            "         },\n" +
            "         {\n" +
            "            \"DocEntry\":2105,\n" +
            "            \"LineId\":3,\n" +
            "            \"VisOrder\":2,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodTipoAnalise\":\"6\",\n" +
            "            \"U_DscTipoAnalise\":\"AVARIADO SOJA 22/23\",\n" +
            "            \"U_ValorEncontrado\":0.0,\n" +
            "            \"U_ValorDestino\":0.0,\n" +
            "            \"U_DscUnidadeMedida\":null,\n" +
            "            \"U_DescontoPeso\":0.0,\n" +
            "            \"U_CodFaixaDesconto\":null,\n" +
            "            \"U_DescontoDestino\":0.0\n" +
            "         }\n" +
            "      ],\n" +
            "      \"AMFS_RETNCollection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETMCollection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR1Collection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR2Collection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR3Collection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR4Collection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR5Collection\":[\n" +
            "         {\n" +
            "            \"DocEntry\":2105,\n" +
            "            \"LineId\":1,\n" +
            "            \"VisOrder\":1,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodContratoPrincipal\":null,\n" +
            "            \"U_CodContratoReservado\":null,\n" +
            "            \"U_Quantidade\":0.0\n" +
            "         }\n" +
            "      ],\n" +
            "      \"AMFS_RETR6Collection\":[\n" +
            "         {\n" +
            "            \"DocEntry\":2105,\n" +
            "            \"LineId\":1,\n" +
            "            \"VisOrder\":1,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodServico\":null,\n" +
            "            \"U_TaxaServico\":0.0\n" +
            "         }\n" +
            "      ],\n" +
            "      \"AMFS_RETR7Collection\":[\n" +
            "         \n" +
            "      ]\n" +
            "   },\n" +
            "   {\n" +
            "      \"DocNum\":2104,\n" +
            "      \"Period\":28,\n" +
            "      \"Instance\":0,\n" +
            "      \"Series\":-1,\n" +
            "      \"Handwrtten\":\"N\",\n" +
            "      \"Status\":\"O\",\n" +
            "      \"RequestStatus\":\"W\",\n" +
            "      \"Creator\":\"BALANCA.SN\",\n" +
            "      \"Remark\":null,\n" +
            "      \"DocEntry\":2104,\n" +
            "      \"Canceled\":\"N\",\n" +
            "      \"Object\":\"AMFS_UDO_RETR\",\n" +
            "      \"LogInst\":null,\n" +
            "      \"UserSign\":94,\n" +
            "      \"Transfered\":\"N\",\n" +
            "      \"CreateDate\":\"2023-02-09\",\n" +
            "      \"CreateTime\":\"15:21:00\",\n" +
            "      \"UpdateDate\":\"2023-02-09\",\n" +
            "      \"UpdateTime\":\"15:21:00\",\n" +
            "      \"DataSource\":\"I\",\n" +
            "      \"U_DtDescarga\":null,\n" +
            "      \"U_CodEndereco\":null,\n" +
            "      \"U_QtdRetida\":0.0,\n" +
            "      \"U_PesagemManual\":\"Y\",\n" +
            "      \"U_PesagemAvulsa\":\"N\",\n" +
            "      \"U_DataPesagem\":\"2023-02-09\",\n" +
            "      \"U_Moeda\":null,\n" +
            "      \"U_TaxaMoeda\":0.0,\n" +
            "      \"U_CodRomaneioOrigem\":null,\n" +
            "      \"U_CodParceiro\":\"CLI0000403\",\n" +
            "      \"U_CodItem\":\"GRA0000002\",\n" +
            "      \"U_EnderecoParceiro\":\"ENTREGA\",\n" +
            "      \"U_DtEmissaoNota\":null,\n" +
            "      \"U_DtEmissaoNotaCA\":null,\n" +
            "      \"U_ReferenciaExterna\":null,\n" +
            "      \"U_CodProgramacaoCarga\":null,\n" +
            "      \"U_CodDocumento\":null,\n" +
            "      \"U_CodDocumentoComp\":null,\n" +
            "      \"U_CodDocumentoCA\":null,\n" +
            "      \"U_CodContrato\":null,\n" +
            "      \"U_CodContratoComplementar\":null,\n" +
            "      \"U_CodViagem\":null,\n" +
            "      \"U_NumeroTicket\":null,\n" +
            "      \"U_Motorista\":\"CARLOS BEZERRA DOS SANTOS\",\n" +
            "      \"U_PlacaCaminhao\":\"DPF-6B89\",\n" +
            "      \"U_UFPlaca\":\"RO\",\n" +
            "      \"U_PlacaCarreta\":\"KEZ-1367\",\n" +
            "      \"U_UFPlacaCarreta\":\"RO\",\n" +
            "      \"U_PlacaCaminhao3\":\"NCK-0833\",\n" +
            "      \"U_UFPlaca3\":\"RO\",\n" +
            "      \"U_NumeroNota\":null,\n" +
            "      \"U_NumeroNotaCA\":null,\n" +
            "      \"U_PesoNota\":0.0,\n" +
            "      \"U_PesoNotaCA\":0.0,\n" +
            "      \"U_ValorNota\":0.0,\n" +
            "      \"U_ValorNotaCA\":0.0,\n" +
            "      \"U_PesoBruto\":0.0,\n" +
            "      \"U_PesoTara\":20190.0,\n" +
            "      \"U_PesoLiquido\":-20190.0,\n" +
            "      \"U_PesoLiquidoDesc\":-20190.0,\n" +
            "      \"U_PesoDestinoDesc\":0.0,\n" +
            "      \"U_PesoLiquidoDest\":0.0,\n" +
            "      \"U_Diferenca\":-20190.0,\n" +
            "      \"U_MassaTotal\":0.0,\n" +
            "      \"U_EncerradoPor\":null,\n" +
            "      \"U_DtEncerramento\":null,\n" +
            "      \"U_HrEncerramento\":null,\n" +
            "      \"U_Status\":\"A\",\n" +
            "      \"U_ChaveNota\":null,\n" +
            "      \"U_ChaveNotaCA\":null,\n" +
            "      \"U_ModeloNota\":null,\n" +
            "      \"U_ModeloNotaCA\":null,\n" +
            "      \"U_SerieNota\":null,\n" +
            "      \"U_SerieNotaCA\":null,\n" +
            "      \"U_CadastradoGuardian\":\"N\",\n" +
            "      \"U_AnaliseConfirmada\":\"N\",\n" +
            "      \"U_RomaneioImpresso\":\"N\",\n" +
            "      \"U_DesbloquearGuardian\":\"N\",\n" +
            "      \"U_AtualizarPesoLiquido\":\"N\",\n" +
            "      \"U_Volume\":0.0,\n" +
            "      \"U_QtdContratoComp\":0.0,\n" +
            "      \"U_NrGuiaFlorestal\":null,\n" +
            "      \"U_CodTransportadora\":\"\",\n" +
            "      \"U_CodMoega\":null,\n" +
            "      \"U_ObservacoesNF\":null,\n" +
            "      \"U_ObservacoesNFCA\":null,\n" +
            "      \"U_ObsRomaneio\":\"EXPEDICAO DE SOJA EM GRAOS NO SECADOR \\rORDEM DE NUMERO 141\",\n" +
            "      \"U_RecusaCarga\":null,\n" +
            "      \"U_QtdRecusada\":0.0,\n" +
            "      \"U_CodVeiculo\":\"172\",\n" +
            "      \"U_CodMotorista\":\"140\",\n" +
            "      \"U_TipoGrao\":null,\n" +
            "      \"U_SubtipoGrao\":null,\n" +
            "      \"U_NFPropria\":null,\n" +
            "      \"U_PesoHectoEncontrado\":0.0,\n" +
            "      \"U_PesoHectoMelhorado\":0.0,\n" +
            "      \"U_Massa20Graus\":0.0,\n" +
            "      \"U_GrauINPM\":0.0,\n" +
            "      \"U_VolumeLaboratorio\":0.0,\n" +
            "      \"U_DiferencaLabExpedido\":0.0,\n" +
            "      \"U_DiferencaLabExpedidoPct\":0.0,\n" +
            "      \"U_CodFilial\":\"2\",\n" +
            "      \"U_HrAnaliseLab\":null,\n" +
            "      \"U_HrAnalise\":null,\n" +
            "      \"U_HoraPesoBruto\":null,\n" +
            "      \"U_HoraPesoTara\":\"15:22:00\",\n" +
            "      \"U_HoraGeracaoNota\":null,\n" +
            "      \"U_HoraEntradaPlanta\":null,\n" +
            "      \"U_NrBoletimColheita\":null,\n" +
            "      \"U_InscricaoEstadual\":null,\n" +
            "      \"U_DesbloqueadoPor\":null,\n" +
            "      \"U_DataDesbloqueio\":null,\n" +
            "      \"U_HoraDesbloqueio\":null,\n" +
            "      \"U_JustificativaDesbloqueio\":null,\n" +
            "      \"U_ValorFrete\":0.0,\n" +
            "      \"U_CodRomaneioGerador\":null,\n" +
            "      \"U_CodOffline\":null,\n" +
            "      \"U_Taxa\":0.0,\n" +
            "      \"U_CodDeposito\":null,\n" +
            "      \"U_DataUltimoAcerto\":null,\n" +
            "      \"U_TaraEmbalagem\":0.0,\n" +
            "      \"U_Impresso\":\"N\",\n" +
            "      \"U_DtPesagemInicial\":null,\n" +
            "      \"U_DtPesagemFinal\":null,\n" +
            "      \"U_HrPesagemInicial\":null,\n" +
            "      \"U_HrPesagemFinal\":null,\n" +
            "      \"U_Estornou\":\"N\",\n" +
            "      \"U_CodPNClassificador\":null,\n" +
            "      \"U_PNClassContrato\":\"N\",\n" +
            "      \"U_CodOrdemCarregamento\":null,\n" +
            "      \"U_CodTipoVeiculo\":\"1\",\n" +
            "      \"U_CodArmazem\":null,\n" +
            "      \"U_CodDocumentoCreditoPresumido\":null,\n" +
            "      \"U_NomeParceiro\":\"CARLOS HENRIQUE MARTINS DE OLIVEIRA\",\n" +
            "      \"U_DescricaoItem\":\"SOJA EM GRAOS\",\n" +
            "      \"U_CodDepositoTransferencia\":null,\n" +
            "      \"U_CodTransferenciaTerceiros\":null,\n" +
            "      \"U_CodLactoFinanceiro\":null,\n" +
            "      \"AMFS_RETACollection\":[\n" +
            "         {\n" +
            "            \"DocEntry\":2104,\n" +
            "            \"LineId\":1,\n" +
            "            \"VisOrder\":0,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodTipoAnalise\":\"5\",\n" +
            "            \"U_DscTipoAnalise\":\"UMIDADE SOJA 22/23\",\n" +
            "            \"U_ValorEncontrado\":0.0,\n" +
            "            \"U_ValorDestino\":0.0,\n" +
            "            \"U_DscUnidadeMedida\":null,\n" +
            "            \"U_DescontoPeso\":0.0,\n" +
            "            \"U_CodFaixaDesconto\":null,\n" +
            "            \"U_DescontoDestino\":0.0\n" +
            "         },\n" +
            "         {\n" +
            "            \"DocEntry\":2104,\n" +
            "            \"LineId\":2,\n" +
            "            \"VisOrder\":1,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodTipoAnalise\":\"7\",\n" +
            "            \"U_DscTipoAnalise\":\"IMPUREZA SOJA 22/23\",\n" +
            "            \"U_ValorEncontrado\":0.0,\n" +
            "            \"U_ValorDestino\":0.0,\n" +
            "            \"U_DscUnidadeMedida\":null,\n" +
            "            \"U_DescontoPeso\":0.0,\n" +
            "            \"U_CodFaixaDesconto\":null,\n" +
            "            \"U_DescontoDestino\":0.0\n" +
            "         },\n" +
            "         {\n" +
            "            \"DocEntry\":2104,\n" +
            "            \"LineId\":3,\n" +
            "            \"VisOrder\":2,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodTipoAnalise\":\"6\",\n" +
            "            \"U_DscTipoAnalise\":\"AVARIADO SOJA 22/23\",\n" +
            "            \"U_ValorEncontrado\":0.0,\n" +
            "            \"U_ValorDestino\":0.0,\n" +
            "            \"U_DscUnidadeMedida\":null,\n" +
            "            \"U_DescontoPeso\":0.0,\n" +
            "            \"U_CodFaixaDesconto\":null,\n" +
            "            \"U_DescontoDestino\":0.0\n" +
            "         }\n" +
            "      ],\n" +
            "      \"AMFS_RETNCollection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETMCollection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR1Collection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR2Collection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR3Collection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR4Collection\":[\n" +
            "         \n" +
            "      ],\n" +
            "      \"AMFS_RETR5Collection\":[\n" +
            "         {\n" +
            "            \"DocEntry\":2104,\n" +
            "            \"LineId\":1,\n" +
            "            \"VisOrder\":0,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodContratoPrincipal\":null,\n" +
            "            \"U_CodContratoReservado\":null,\n" +
            "            \"U_Quantidade\":0.0\n" +
            "         }\n" +
            "      ],\n" +
            "      \"AMFS_RETR6Collection\":[\n" +
            "         {\n" +
            "            \"DocEntry\":2104,\n" +
            "            \"LineId\":1,\n" +
            "            \"VisOrder\":0,\n" +
            "            \"Object\":\"AMFS_UDO_RETR\",\n" +
            "            \"LogInst\":null,\n" +
            "            \"U_CodServico\":null,\n" +
            "            \"U_TaxaServico\":0.0\n" +
            "         }\n" +
            "      ],\n" +
            "      \"AMFS_RETR7Collection\":[\n" +
            "         \n" +
            "      ]\n" +
            "   }\n" +
            "]"
}