name: Release Notifier Action

on:
  push:
jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.MAIL_SMTP_ADDRESS}}
        server_port: ${{secrets.MAIL_PORT}}
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        to: ${{secrets.MAIL_TO_LIST}}
        from: ${{secrets.MAIL_USERNAME}}
        body: Build job of ${{github.repository}} completed successfully!
        #html_body: file://README.html
        reply_to: ${{secrets.MAIL_USERNAME}}
        convert_markdown: true
        priority: low