name: Push Release Candidate to Docker Hub

on:
  workflow_dispatch:
env:
  FULL_IMAGE_NAME: malacration/sap-service

jobs:
  push_rc_to_registry:
    name: Build and Push RC Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for RC image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.FULL_IMAGE_NAME }}
          tags: |
            type=raw,value=rc-${{ github.event.number }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MY_VERSION=rc-${{ github.event.number }}
            MY_BUILTBY=github-action
